/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jyotividyalaya;

import java.awt.Color;

/**
 *
 * @author deva
 */
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import javax.swing.JOptionPane;
import java.sql.*;
import java.sql.ResultSet;


public class admission extends javax.swing.JFrame {

    /**
     * Creates new form admission
     */
    public admission() {
        initComponents();
         jButton1.setBackground(new Color(0,0,0,0));
        
       jButton1.setBorder(null);
       jButton2.setBackground(new Color(0,0,0,0));
        
       jButton2.setBorder(null);
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField8 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jTextField12 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField14 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        jTextField8.setBackground(javax.swing.UIManager.getDefaults().getColor("InternalFrame.activeTitleGradient"));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        setMinimumSize(new java.awt.Dimension(830, 700));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(116, 61, 43));
        jPanel2.setLayout(null);

        jLabel14.setFont(new java.awt.Font("Cambria Math", 1, 36)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("ADMISSION FORM");
        jPanel2.add(jLabel14);
        jLabel14.setBounds(150, 10, 330, 40);

        jLabel1.setFont(new java.awt.Font("Ninja Garden Halftone", 0, 18)); // NOI18N
        jLabel1.setText("STUDENT ID");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(20, 50, 200, 80);

        jTextField1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTextField1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel2.add(jTextField1);
        jTextField1.setBounds(140, 80, 350, 30);

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -6, 620, 120));

        jPanel3.setBackground(new java.awt.Color(245, 222, 179));
        jPanel3.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Ninja Garden Halftone", 0, 18)); // NOI18N
        jLabel2.setText("NAME");
        jPanel3.add(jLabel2);
        jLabel2.setBounds(10, 20, 190, 30);

        jLabel15.setFont(new java.awt.Font("Ninja Garden Halftone", 0, 18)); // NOI18N
        jLabel15.setText("FATHER'S NAME");
        jPanel3.add(jLabel15);
        jLabel15.setBounds(10, 50, 190, 30);

        jLabel3.setFont(new java.awt.Font("Ninja Garden Halftone", 0, 18)); // NOI18N
        jLabel3.setText("MOTHER'S NAME");
        jPanel3.add(jLabel3);
        jLabel3.setBounds(10, 90, 190, 30);

        jLabel4.setFont(new java.awt.Font("Ninja Garden Halftone", 0, 18)); // NOI18N
        jLabel4.setText("PHONE NO.");
        jPanel3.add(jLabel4);
        jLabel4.setBounds(10, 130, 190, 30);

        jLabel5.setFont(new java.awt.Font("Ninja Garden Halftone", 0, 18)); // NOI18N
        jLabel5.setText("EMAIL ID");
        jPanel3.add(jLabel5);
        jLabel5.setBounds(10, 160, 190, 30);

        jLabel6.setFont(new java.awt.Font("Ninja Garden Halftone", 0, 18)); // NOI18N
        jLabel6.setText("ADDHAR NO.");
        jPanel3.add(jLabel6);
        jLabel6.setBounds(10, 190, 190, 30);

        jLabel7.setFont(new java.awt.Font("Ninja Garden Halftone", 0, 18)); // NOI18N
        jLabel7.setText("GENDER");
        jPanel3.add(jLabel7);
        jLabel7.setBounds(10, 220, 190, 30);

        jLabel8.setFont(new java.awt.Font("Ninja Garden Halftone", 0, 18)); // NOI18N
        jLabel8.setText("ADDRESS");
        jPanel3.add(jLabel8);
        jLabel8.setBounds(10, 250, 190, 30);

        jLabel9.setFont(new java.awt.Font("Ninja Garden Halftone", 0, 18)); // NOI18N
        jLabel9.setText("CASTE");
        jPanel3.add(jLabel9);
        jLabel9.setBounds(10, 280, 190, 30);

        jLabel10.setFont(new java.awt.Font("Ninja Garden Halftone", 0, 18)); // NOI18N
        jLabel10.setText("D.O.B");
        jPanel3.add(jLabel10);
        jLabel10.setBounds(10, 310, 190, 30);

        jLabel11.setFont(new java.awt.Font("Ninja Garden Halftone", 0, 18)); // NOI18N
        jLabel11.setText("OCCUPATION :-");
        jPanel3.add(jLabel11);
        jLabel11.setBounds(10, 340, 190, 30);

        jLabel12.setFont(new java.awt.Font("Ninja Garden Halftone", 0, 18)); // NOI18N
        jLabel12.setText("FATHER's");
        jPanel3.add(jLabel12);
        jLabel12.setBounds(80, 360, 190, 30);

        jLabel13.setFont(new java.awt.Font("Ninja Garden Halftone", 0, 18)); // NOI18N
        jLabel13.setText("MOTHER's");
        jPanel3.add(jLabel13);
        jLabel13.setBounds(80, 390, 190, 30);

        jRadioButton1.setFont(new java.awt.Font("Ninja Garden Halftone", 0, 14)); // NOI18N
        jRadioButton1.setText("MALE");
        jPanel3.add(jRadioButton1);
        jRadioButton1.setBounds(210, 220, 90, 27);

        jRadioButton2.setFont(new java.awt.Font("Ninja Garden Halftone", 0, 14)); // NOI18N
        jRadioButton2.setText("FEMALE");
        jPanel3.add(jRadioButton2);
        jRadioButton2.setBounds(310, 220, 100, 27);

        jTextField12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTextField12.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel3.add(jTextField12);
        jTextField12.setBounds(220, 390, 160, 20);

        jTextField2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTextField2.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel3.add(jTextField2);
        jTextField2.setBounds(210, 20, 200, 20);

        jTextField3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTextField3.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel3.add(jTextField3);
        jTextField3.setBounds(210, 50, 200, 20);

        jTextField4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTextField4.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel3.add(jTextField4);
        jTextField4.setBounds(210, 90, 200, 20);

        jTextField5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTextField5.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel3.add(jTextField5);
        jTextField5.setBounds(210, 130, 200, 20);

        jTextField6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTextField6.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel3.add(jTextField6);
        jTextField6.setBounds(210, 160, 200, 20);

        jTextField7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTextField7.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel3.add(jTextField7);
        jTextField7.setBounds(210, 190, 200, 18);

        jTextField14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTextField14.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextField14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField14ActionPerformed(evt);
            }
        });
        jPanel3.add(jTextField14);
        jTextField14.setBounds(210, 250, 270, 18);

        jTextField9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTextField9.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextField9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField9ActionPerformed(evt);
            }
        });
        jPanel3.add(jTextField9);
        jTextField9.setBounds(210, 280, 160, 20);

        jTextField10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTextField10.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextField10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField10ActionPerformed(evt);
            }
        });
        jPanel3.add(jTextField10);
        jTextField10.setBounds(210, 310, 160, 18);

        jTextField11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTextField11.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel3.add(jTextField11);
        jTextField11.setBounds(220, 360, 160, 20);

        jButton1.setFont(new java.awt.Font("Ninja Garden Halftone", 0, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/button (13).png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1);
        jButton1.setBounds(220, 440, 140, 50);

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 620, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField14ActionPerformed

    private void jTextField9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField9ActionPerformed

    private void jTextField10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField10ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try{
            Class.forName("java.sql.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/schoolmanagement","root","mysql");
            Statement stm=con.createStatement();
            String gender=null;

            if(jRadioButton1.isSelected()){
                gender=jRadioButton1.getText();
            }

            else

            if(jRadioButton2.isSelected()){
                gender=jRadioButton2.getText();

            }
            String a=jTextField1.getText();
            String b=jTextField2.getText();
            String c=jTextField3.getText();
            String d=jTextField4.getText();
            String e=jTextField5.getText();
            String f=jTextField6.getText();
            String g=jTextField7.getText();
            String h=jTextField8.getText();
            String i=jTextField9.getText();
            String j=jTextField10.getText();
            String k=jTextField11.getText();
            String l=jTextField12.getText();

            String sql;
            sql= "insert into details values('"+a+"','"+b+"','"+c+"','"+d+"','"+e+"','"+f+"','"+gender+"','"+g+"','"+h+"','"+i+"','"+j+"','"+k+"','"+l+"')";
            System.out.print(sql);
            int r=stm.executeUpdate(sql);
            if(r>0){
                JOptionPane.showMessageDialog(null,"Record Inserted");
            }
            else{
                JOptionPane.showMessageDialog(null,"Record not Inserted");
            }
            jTextField1.setText(null);
            jTextField2.setText(null);
            jTextField3.setText(null);
            jTextField4.setText(null);
            jTextField5.setText(null);
            jTextField6.setText(null);
            jTextField7.setText(null);

            jTextField8.setText(null);
            jTextField9.setText(null);
            jTextField10.setText(null);
            jTextField11.setText(null);
            jTextField12.setText(null);

            jRadioButton1.setSelected(false);
            jRadioButton2.setSelected(false);

        }

        catch(Exception e){
            JOptionPane.showMessageDialog(null,e.getMessage());
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(admission.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(admission.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(admission.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(admission.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new admission().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
