/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jyotividyalaya;

import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author deva
 */
public class fees extends javax.swing.JFrame {

    /**
     * Creates new form fees
     */
    public fees() {
        initComponents();
        
        jButton1.setBackground(new Color(0,0,0,0));
        
       jButton1.setBorder(null);
       jButton2.setBackground(new Color(0,0,0,0));
        
       jButton2.setBorder(null);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        NAME = new javax.swing.JLabel();
        FEES = new javax.swing.JLabel();
        DATE = new javax.swing.JLabel();
        CLASS = new javax.swing.JLabel();
        FATHER = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        fname = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        fee = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        fee1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(245, 222, 179));
        jPanel1.setLayout(null);

        NAME.setFont(new java.awt.Font("Ninja Garden Halftone", 1, 18)); // NOI18N
        NAME.setText("FULL NAME");
        jPanel1.add(NAME);
        NAME.setBounds(20, 130, 152, 49);

        FEES.setFont(new java.awt.Font("Ninja Garden Halftone", 1, 18)); // NOI18N
        FEES.setText("TOTAL FEES");
        jPanel1.add(FEES);
        FEES.setBounds(20, 400, 152, 49);

        DATE.setFont(new java.awt.Font("Ninja Garden Halftone", 1, 18)); // NOI18N
        DATE.setText("DATE");
        jPanel1.add(DATE);
        DATE.setBounds(20, 340, 152, 49);

        CLASS.setFont(new java.awt.Font("Ninja Garden Halftone", 1, 18)); // NOI18N
        CLASS.setText("CLASS");
        jPanel1.add(CLASS);
        CLASS.setBounds(20, 270, 152, 49);

        FATHER.setFont(new java.awt.Font("Ninja Garden Halftone", 1, 18)); // NOI18N
        FATHER.setText("FATHER NAME");
        jPanel1.add(FATHER);
        FATHER.setBounds(20, 200, 152, 49);

        name.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(name);
        name.setBounds(250, 130, 335, 49);

        fname.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(fname);
        fname.setBounds(250, 200, 335, 49);

        jTextField3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jTextField3);
        jTextField3.setBounds(250, 270, 335, 49);

        fee.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        fee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                feeActionPerformed(evt);
            }
        });
        jPanel1.add(fee);
        fee.setBounds(250, 340, 335, 49);

        jPanel2.setBackground(new java.awt.Color(116, 61, 43));
        jPanel2.setLayout(null);

        jLabel14.setBackground(new java.awt.Color(116, 61, 43));
        jLabel14.setFont(new java.awt.Font("Cambria Math", 1, 48)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText(" FEE PAYMENT");
        jPanel2.add(jLabel14);
        jLabel14.setBounds(180, 20, 370, 50);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 700, 114);

        jButton1.setFont(new java.awt.Font("Ninja Garden Halftone", 0, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/button (13).png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(320, 470, 130, 50);

        fee1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        fee1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fee1ActionPerformed(evt);
            }
        });
        jPanel1.add(fee1);
        fee1.setBounds(250, 400, 335, 49);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void feeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_feeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_feeActionPerformed

    private void fee1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fee1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fee1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
try{
            Class.forName("java.sql.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/schoolmanagementl","root","divakar");
            Statement stm=con.createStatement();
            String gender=null;

         
            String a=name.getText();
            String b=fname.getText();
            String c=jTextField3.getText();
            String d=fee.getText();
            String e=fee1.getText();
           

            String sql;
            sql= "insert into fee values('"+a+"','"+b+"','"+c+"','"+d+"','"+e+"')";
            System.out.print(sql);
            int r=stm.executeUpdate(sql);
            if(r>0){
                JOptionPane.showMessageDialog(null,"Record Inserted");
            }
            else{
                JOptionPane.showMessageDialog(null,"Record not Inserted");
            }
            name.setText(null);
          fname.setText(null);
            jTextField3.setText(null);
            fee.setText(null);
            fee1.setText(null);
          

        }

        catch(Exception e){
            JOptionPane.showMessageDialog(null,e.getMessage());
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fees.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fees.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fees.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fees.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new fees().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CLASS;
    private javax.swing.JLabel DATE;
    private javax.swing.JLabel FATHER;
    private javax.swing.JLabel FEES;
    private javax.swing.JLabel NAME;
    private javax.swing.JTextField fee;
    private javax.swing.JTextField fee1;
    private javax.swing.JTextField fname;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField name;
    // End of variables declaration//GEN-END:variables
}
